language: php
php:
  - 5.3
  - 5.4
env:
  - RESQUE_CLIENT_TYPE=predis
  - RESQUE_CLIENT_TYPE=credis
  - RESQUE_CLIENT_TYPE=phpredis
  - RESQUE_CLIENT_TYPE=phpiredis
before_script:
  - sh -c "if [ $RESQUE_CLIENT_TYPE == 'phpredis' ]; then wget https://github.com/nicolasff/phpredis/archive/master.zip -O php-redis.zip && unzip php-redis.zip; fi"
  - sh -c "if [ $RESQUE_CLIENT_TYPE == 'phpredis' ]; then cd phpredis-master/ && phpize && ./configure && make && make install; fi"
  - sh -c "if [ $RESQUE_CLIENT_TYPE == 'phpredis' ]; then echo \"extension=redis.so\" >> `php --ini | grep \"Loaded Configuration\" | sed -e \"s|.*:\s*||\"`; fi"
  - sh -c "if [ $RESQUE_CLIENT_TYPE == 'phpiredis' ]; then wget https://github.com/redis/hiredis/archive/master.zip -O hiredis.zip && unzip hiredis.zip; fi"
  - sh -c "if [ $RESQUE_CLIENT_TYPE == 'phpiredis' ]; then wget https://github.com/nrk/phpiredis/archive/master.zip -O php-redis.zip && unzip php-redis.zip; fi"
  - sh -c "if [ $RESQUE_CLIENT_TYPE == 'phpiredis' ]; then cd phpiredis-master/ && phpize && ./configure --enable-phpiredis --with-hiredis-dir=../hiredis && make && make install; fi"
  - sh -c "if [ $RESQUE_CLIENT_TYPE == 'phpiredis' ]; then echo \"extension=phpiredis.so\" >> `php --ini | grep \"Loaded Configuration\" | sed -e \"s|.*:\s*||\"`; fi"

  - composer install

https://github.com//archive/master.zip
